name: Deployment

on:
  push:
    branches:
      - master
jobs:
  lint:
    name: Deploy to firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install node_modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Prepare env file
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: echo $ENV_FILE > .env
      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          export $(cat .env | xargs)
          yarn deploy
